# Generated by Django 3.2.7 on 2022-01-18 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profilepage', '0002_auto_20220118_1607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='classroom',
        ),
        migrations.AddField(
            model_name='classroom',
            name='teachers',
            field=models.ManyToManyField(to='profilepage.Teacher'),
        ),
    ]
