# Generated by Django 3.2.7 on 2022-01-19 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profilepage', '0004_auto_20220119_0915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='teachers',
        ),
        migrations.AddField(
            model_name='classroom',
            name='teacher',
            field=models.ForeignKey(default="1", on_delete=django.db.models.deletion.CASCADE, to='profilepage.teacher'),
            preserve_default=False,
        ),
    ]
