# Generated by Django 3.2.7 on 2022-02-09 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profilepage', '0005_auto_20220119_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='courses',
            field=models.ManyToManyField(blank=True, to='profilepage.Course'),
        ),
        migrations.CreateModel(
            name='Sub_chapters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subchapter_name', models.CharField(max_length=40)),
                ('parent_chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profilepage.chapters')),
            ],
        ),
    ]
