# Generated by Django 3.2.7 on 2022-02-09 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profilepage', '0006_auto_20220209_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='sub_chapters',
            name='content',
            field=models.CharField(default=1, max_length=5000),
            preserve_default=False,
        ),
    ]
