# Generated by Django 3.2.7 on 2022-02-09 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profilepage', '0007_sub_chapters_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subchapters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subchapter_name', models.CharField(max_length=40)),
                ('content', models.TextField(max_length=5000)),
                ('parent_chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profilepage.chapters')),
            ],
        ),
        migrations.DeleteModel(
            name='Sub_chapters',
        ),
    ]
