# Generated by Django 3.2.7 on 2022-02-11 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profilepage', '0009_alter_subchapters_parent_chapter'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapters',
            name='chapter_number',
            field=models.IntegerField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subchapters',
            name='subchapter_number',
            field=models.IntegerField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
