# Generated by Django 3.2.7 on 2022-02-14 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_remove_videos_parent_chapter'),
        ('profilepage', '0010_auto_20220211_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='subchapters',
            name='video',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='courses.videos'),
            preserve_default=False,
        ),
    ]
