# Generated by Django 3.2.7 on 2022-02-14 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profilepage', '0011_subchapters_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapters',
            name='chapter_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='subchapters',
            name='subchapter_number',
            field=models.IntegerField(),
        ),
    ]
