# Generated by Django 3.2.7 on 2022-02-14 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_quiz'),
        ('profilepage', '0012_auto_20220214_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='subchapters',
            name='quiz',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='courses.quiz'),
            preserve_default=False,
        ),
    ]
