# Generated by Django 3.2.7 on 2022-02-14 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profilepage', '0014_alter_subchapters_quiz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subchapters',
            name='quiz',
        ),
    ]
