# Generated by Django 3.2.7 on 2022-02-25 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profilepage', '0015_remove_subchapters_quiz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='license_active',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
