# Generated by Django 3.2.7 on 2022-05-19 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profilepage', '0016_alter_student_license_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Excercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deadline', models.DateTimeField(auto_now_add=True)),
                ('excercise_type', models.CharField(max_length=10)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profilepage.classroom')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profilepage.course')),
                ('subchapters', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profilepage.subchapters')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profilepage.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='ExcerciseResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turned_in', models.BooleanField()),
                ('turned_in_data', models.DateField(auto_now=True)),
                ('excercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profilepage.excercise')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profilepage.student')),
            ],
        ),
    ]
