# Generated by Django 3.2.7 on 2022-05-19 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0025_merge_20220517_1511'),
        ('profilepage', '0017_excercise_excerciseresult'),
    ]

    operations = [
        migrations.RenameField(
            model_name='excercise',
            old_name='subchapters',
            new_name='subchapter',
        ),
        migrations.RemoveField(
            model_name='excercise',
            name='excercise_type',
        ),
        migrations.AddField(
            model_name='excercise',
            name='fill_excercise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.fillinblanks'),
        ),
        migrations.AddField(
            model_name='excercise',
            name='quiz_excercise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.quiz'),
        ),
        migrations.AddField(
            model_name='excercise',
            name='read_excercise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.visitedpage'),
        ),
        migrations.AddField(
            model_name='excercise',
            name='video_excercise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.videowatched'),
        ),
    ]
