# Generated by Django 3.2.7 on 2022-05-19 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profilepage', '0018_auto_20220519_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excercise',
            name='deadline',
            field=models.DateField(),
        ),
    ]
