# Generated by Django 3.2.7 on 2022-05-19 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profilepage', '0019_alter_excercise_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='excercise',
            name='excercise_type',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
    ]
