# Generated by Django 3.2.7 on 2022-05-20 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0027_videos_parent'),
        ('profilepage', '0020_excercise_excercise_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excercise',
            name='read_excercise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='excercise_subchapter', to='profilepage.subchapters'),
        ),
        migrations.AlterField(
            model_name='excercise',
            name='video_excercise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.videos'),
        ),
    ]
