# Generated by Django 3.2.7 on 2022-02-14 10:04

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_title', models.CharField(max_length=50)),
                ('video_descp', models.CharField(max_length=200)),
                ('video', embed_video.fields.EmbedVideoField()),
            ],
        ),
    ]
