# Generated by Django 3.2.7 on 2022-02-14 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_videos_parent_chapter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videos',
            name='parent_chapter',
        ),
    ]
