# Generated by Django 3.2.7 on 2022-02-14 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_quiz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='quiz_name',
        ),
    ]
