# Generated by Django 3.2.7 on 2022-02-14 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_remove_quiz_quiz_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='group_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
