# Generated by Django 3.2.7 on 2022-02-14 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profilepage', '0015_remove_subchapters_quiz'),
        ('courses', '0006_quiz_group_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='group_name',
        ),
        migrations.AddField(
            model_name='quiz',
            name='parent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='profilepage.subchapters'),
            preserve_default=False,
        ),
    ]
