# Generated by Django 3.2.7 on 2022-03-14 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profilepage', '0016_alter_student_license_active'),
        ('courses', '0010_rename_quiz_result_quizresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='FillInBlanks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=200, null=True)),
                ('code', models.CharField(max_length=1000)),
                ('answer', models.CharField(max_length=100, null=True)),
                ('hint', models.CharField(max_length=500)),
                ('subchapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profilepage.subchapters')),
            ],
        ),
    ]
