# Generated by Django 3.2.7 on 2022-03-14 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_alter_fillinblanks_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='fillinblanks',
            name='input_length',
            field=models.CharField(default=10, max_length=15),
            preserve_default=False,
        ),
    ]
