# Generated by Django 3.2.7 on 2022-03-14 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_fillinblanks_input_length'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fillinblanks',
            name='code',
        ),
        migrations.AddField(
            model_name='fillinblanks',
            name='code_after',
            field=models.TextField(default=15, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fillinblanks',
            name='code_before',
            field=models.TextField(default=15, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fillinblanks',
            name='input_length',
            field=models.CharField(max_length=50),
        ),
    ]
