# Generated by Django 3.2.7 on 2022-03-14 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_auto_20220314_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='fillinblanks',
            name='code_on_input_line_after',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fillinblanks',
            name='code_on_input_line_before',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
