# Generated by Django 3.2.7 on 2022-03-14 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_auto_20220314_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fillinblanks',
            name='code_after',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
