# Generated by Django 3.2.7 on 2022-03-14 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_alter_fillinblanks_code_after'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fillinblanks',
            name='answer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
