# Generated by Django 3.2.7 on 2022-03-14 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_alter_fillinblanks_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fillinblanks',
            name='answer',
            field=models.CharField(blank=True, default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fillinblanks',
            name='code_after',
            field=models.TextField(blank=True, default=1, max_length=500),
            preserve_default=False,
        ),
    ]
