# Generated by Django 3.2.7 on 2022-03-15 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profilepage', '0016_alter_student_license_active'),
        ('courses', '0018_auto_20220314_1556'),
    ]

    operations = [
        migrations.CreateModel(
            name='FillInBlanksResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=50)),
                ('result', models.IntegerField()),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.fillinblanks')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profilepage.student')),
            ],
        ),
    ]
