# Generated by Django 3.2.7 on 2022-03-23 09:14

import courses.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0019_fillinblanksresults'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fillinblanks',
            name='code_after',
            field=courses.fields.NonStrippingTextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='fillinblanks',
            name='code_before',
            field=courses.fields.NonStrippingTextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='fillinblanks',
            name='code_on_input_line_after',
            field=courses.fields.NonStrippingTextField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='fillinblanks',
            name='code_on_input_line_before',
            field=courses.fields.NonStrippingTextField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='fillinblanks',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='fillinblanks',
            name='input_length',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
