# Generated by Django 3.2.7 on 2022-03-23 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profilepage', '0016_alter_student_license_active'),
        ('courses', '0020_auto_20220323_1014'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitedPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.URLField()),
                ('visited', models.BooleanField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profilepage.student')),
            ],
        ),
    ]
