# Generated by Django 3.2.7 on 2022-03-23 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profilepage', '0016_alter_student_license_active'),
        ('courses', '0022_visitedpage_subchapter'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoWatched',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watched', models.BooleanField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profilepage.student')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.videos')),
            ],
        ),
    ]
