# Generated by Django 3.2.12 on 2022-03-25 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0020_auto_20220322_2059'),
        ('courses', '0023_videowatched'),
    ]

    operations = [
    ]
