# Generated by Django 3.2.7 on 2022-05-17 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0020_auto_20220322_2059'),
        ('courses', '0024_videowatched_watchtime'),
    ]

    operations = [
    ]
