# Generated by Django 3.2.7 on 2022-05-19 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profilepage', '0019_alter_excercise_deadline'),
        ('courses', '0025_merge_20220517_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='videowatched',
            name='parent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='profilepage.subchapters'),
            preserve_default=False,
        ),
    ]
