# Generated by Django 3.2.7 on 2022-05-20 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profilepage', '0020_excercise_excercise_type'),
        ('courses', '0026_videowatched_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='parent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='profilepage.subchapters'),
            preserve_default=False,
        ),
    ]
