# Generated by Django 3.2.7 on 2022-05-20 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profilepage', '0021_auto_20220520_0931'),
        ('courses', '0027_videos_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fillinblanks',
            name='subchapter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='profilepage.subchapters'),
        ),
        migrations.AlterField(
            model_name='fillinblanksresults',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.fillinblanks'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='profilepage.subchapters'),
        ),
        migrations.AlterField(
            model_name='quizresult',
            name='quiz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.quiz'),
        ),
        migrations.AlterField(
            model_name='quizresult',
            name='students',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='profilepage.student'),
        ),
        migrations.AlterField(
            model_name='videos',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='profilepage.subchapters'),
        ),
        migrations.AlterField(
            model_name='visitedpage',
            name='subchapter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='profilepage.subchapters'),
        ),
    ]
